version: "3.4"
services:
  neo4j:
   image: neo4j:3.0
  # network_mode: host
   ports:
    - 7474:7474
    - 7687:7687
   volumes:
     - ~/neo4j/data:/data
     - ~/neo4j/logs:/logs

  jupyter:
   image: jupyter/scipy-notebook
   ports:
    - 8889:8888
   volumes:
     - ${PWD}/work:/home/jovyan/work
   entrypoint: ["jupyter", "notebook", "--port=8888", "--ip=0.0.0.0"]
  
